# permissions for end users to view storagevirtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagevirtualmachine-viewer-role
rules:
- apiGroups:
  - ontap.vaughanross.io
  resources:
  - storagevirtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ontap.vaughanross.io
  resources:
  - storagevirtualmachines/status
  verbs:
  - get
