# permissions for end users to view volumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-viewer-role
rules:
- apiGroups:
  - ontap.vaughanross.io
  resources:
  - volumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ontap.vaughanross.io
  resources:
  - volumes/status
  verbs:
  - get
